### PR TITLE
Only save the transformed output file if it's different from the original input file

### PR DESCRIPTION
**Pull request by chris-peterson**
We had IIS process reset issues when web.config was touched even if there were no changes.

### CODE REVIEW

**Comment by chris-peterson** [comment]
@Novakov -- think you could merge this in?  I've been maintaining a fork for quite a while with just this 1 change...

**Comment by Novakov** [comment]
Oh my... I totally forgot about this repository. If you would like, I can transfer ownership of this repo (and NuGet package too) to you, as I'm no longer in need of this tool.

**Comment by chris-peterson** [comment]
sure.  I'd be happy to take it over.  it's been a useful tool for me -- thanks for creating it!

**Comment by Novakov** [comment]
Great. I've added you as an owner of NuGet package and collaborator in this project. I can't transfer ownership of repository to you as you already have repository called 'xmltransform'. I will merge this PR, than you can delete your repository and I will transfer it to you.

**Pull request merged**
